### ISSUE TITLE
Couldn't install per docs

### ISSUE THREAD

**Issue by Eihcir0** [pbshgthm/blacksmith#1]
Steps to repo:

```
 ~/dev $ mkdir test
 ~/dev $ cd test
 ~/dev/test $ forge init
Initializing /Users/devtooligan/dev/test...
{...}
Done.
 ~/dev/test  master $ forge build
success.
 ~/dev/test  master $ curl -O https://raw.githubusercontent.com/pbshgthm/blacksmith/main/blacksmith.js
node blacksmith.js create #in foundry project's root directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6917  100  6917    0     0  17788      0 --:--:-- --:--:-- --:--:-- 18060
running :: forge build
build   :: failed
found   :: 1 contracts

node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, open './out/Contract.sol/0.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at getABI (/Users/devtooligan/dev/test/blacksmith.js:36:26)
    at /Users/devtooligan/dev/test/blacksmith.js:234:21
    at Array.forEach (<anonymous>)
    at createBlacksmiths (/Users/devtooligan/dev/test/blacksmith.js:233:11)
    at /Users/devtooligan/dev/test/blacksmith.js:19:17
    at ChildProcess.exithandler (node:child_process:388:7)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './out/Contract.sol/0.json'
}
```

fwiw I got the same error on an existing repo as well...

**Comment by pbshgthm** [comment]
Hi, looks like the error is because there is no code in the contract. The generated ABI is empty. Can you add some code to `Contract.sol`?

**Comment by pbshgthm** [comment]
Can you share the `cache/solidity-files-cache.json` file? Also, can you share your foundry version `forge --version`

**Comment by devtooligan** [comment]
`$ forge --version` 
```
foundry-cli 0.1.0
```
`$ cat cache/solidity-files-cache.json`
```
{
  "_format": "ethers-rs-sol-cache-1",
  "files": {
    "/Users/devtooligan/dev/test/src/Contract.sol": {
      "lastModificationDate": 1645156267759,
      "contentHash": "338c2b456417869f11b228de3b3fbaed",
      "sourceName": "src/Contract.sol",
      "solcConfig": {
        "settings": {
          "optimizer": {
            "enabled": false,
            "runs": 200
          },
          "outputSelection": {
            "*": {
              "": [
                "ast"
              ],
              "*": [
                "abi",
                "evm.bytecode",
                "evm.deployedBytecode",
                "evm.methodIdentifiers"
              ]
            }
          },
          "evmVersion": "london"
        }
      },
      "imports": [],
      "versionPragmas": [
        "0.8.10"
      ],
      "artifacts": [
        "Contract"
      ]
    },
    "/Users/devtooligan/dev/test/src/test/Contract.t.sol": {
      "lastModificationDate": 1645156267759,
      "contentHash": "5ce497c2d0d00f52e09ab63326c63aef",
      "sourceName": "src/test/Contract.t.sol",
      "solcConfig": {
        "settings": {
          "optimizer": {
            "enabled": false,
            "runs": 200
          },
          "outputSelection": {
            "*": {
              "": [
                "ast"
              ],
              "*": [
                "abi",
                "evm.bytecode",
                "evm.deployedBytecode",
                "evm.methodIdentifiers"
              ]
            }
          },
          "evmVersion": "london"
        }
      },
      "imports": [
        "ds-test/test.sol"
      ],
      "versionPragmas": [
        "0.8.10"
      ],
      "artifacts": [
        "ContractTest"
      ]
    }
  }
}%
```

**Comment by pbshgthm** [comment]
Looks like its a different version of forge. Can you update foundry using `foundryup`?

**Comment by devtooligan** [comment]
your probably right.  moving to foundry support.  will try to install this later. bummer
